/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DataShare API
 * API de transfert de fichiers DataShare (US01-US10)
 * OpenAPI spec version: 1.0.0
 */

export type FilesControllerUploadBody = {
  file: Blob;
  expiresInDays?: number;
  password?: string;
  /** Tags séparés par des virgules */
  tags?: string;
};
