/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DataShare API
 * API de transfert de fichiers DataShare (US01-US10)
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  FileMetadataDto,
  FileSummaryDto,
  FilesControllerHistoryParams,
  FilesControllerUploadBody,
  UploadResultDto,
  VerifyPasswordDto,
  VerifyPasswordResultDto,
} from "./models";

import { customInstance } from "../core/api-client";

export const filesControllerUpload = (
  filesControllerUploadBody: FilesControllerUploadBody,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append(`file`, filesControllerUploadBody.file);
  if (filesControllerUploadBody.expiresInDays !== undefined) {
    formData.append(
      `expiresInDays`,
      filesControllerUploadBody.expiresInDays.toString(),
    );
  }
  if (filesControllerUploadBody.password !== undefined) {
    formData.append(`password`, filesControllerUploadBody.password);
  }
  if (filesControllerUploadBody.tags !== undefined) {
    formData.append(`tags`, filesControllerUploadBody.tags);
  }

  return customInstance<UploadResultDto>({
    url: `/api/files`,
    method: "POST",
    headers: { "Content-Type": "multipart/form-data" },
    data: formData,
    signal,
  });
};

export const getFilesControllerUploadMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof filesControllerUpload>>,
    TError,
    { data: FilesControllerUploadBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof filesControllerUpload>>,
  TError,
  { data: FilesControllerUploadBody },
  TContext
> => {
  const mutationKey = ["filesControllerUpload"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof filesControllerUpload>>,
    { data: FilesControllerUploadBody }
  > = (props) => {
    const { data } = props ?? {};

    return filesControllerUpload(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type FilesControllerUploadMutationResult = NonNullable<
  Awaited<ReturnType<typeof filesControllerUpload>>
>;
export type FilesControllerUploadMutationBody = FilesControllerUploadBody;
export type FilesControllerUploadMutationError = unknown;

export const useFilesControllerUpload = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof filesControllerUpload>>,
      TError,
      { data: FilesControllerUploadBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof filesControllerUpload>>,
  TError,
  { data: FilesControllerUploadBody },
  TContext
> => {
  const mutationOptions = getFilesControllerUploadMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const filesControllerHistory = (
  params: FilesControllerHistoryParams,
  signal?: AbortSignal,
) => {
  return customInstance<FileSummaryDto[]>({
    url: `/api/files`,
    method: "GET",
    params,
    signal,
  });
};

export const getFilesControllerHistoryQueryKey = (
  params?: FilesControllerHistoryParams,
) => {
  return [`/api/files`, ...(params ? [params] : [])] as const;
};

export const getFilesControllerHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof filesControllerHistory>>,
  TError = unknown,
>(
  params: FilesControllerHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filesControllerHistory>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFilesControllerHistoryQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof filesControllerHistory>>
  > = ({ signal }) => filesControllerHistory(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof filesControllerHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FilesControllerHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof filesControllerHistory>>
>;
export type FilesControllerHistoryQueryError = unknown;

export function useFilesControllerHistory<
  TData = Awaited<ReturnType<typeof filesControllerHistory>>,
  TError = unknown,
>(
  params: FilesControllerHistoryParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filesControllerHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerHistory>>,
          TError,
          Awaited<ReturnType<typeof filesControllerHistory>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFilesControllerHistory<
  TData = Awaited<ReturnType<typeof filesControllerHistory>>,
  TError = unknown,
>(
  params: FilesControllerHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filesControllerHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerHistory>>,
          TError,
          Awaited<ReturnType<typeof filesControllerHistory>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFilesControllerHistory<
  TData = Awaited<ReturnType<typeof filesControllerHistory>>,
  TError = unknown,
>(
  params: FilesControllerHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filesControllerHistory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFilesControllerHistory<
  TData = Awaited<ReturnType<typeof filesControllerHistory>>,
  TError = unknown,
>(
  params: FilesControllerHistoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filesControllerHistory>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFilesControllerHistoryQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const filesControllerMetadata = (
  token: string,
  signal?: AbortSignal,
) => {
  return customInstance<FileMetadataDto>({
    url: `/api/files/${token}`,
    method: "GET",
    signal,
  });
};

export const getFilesControllerMetadataQueryKey = (token?: string) => {
  return [`/api/files/${token}`] as const;
};

export const getFilesControllerMetadataQueryOptions = <
  TData = Awaited<ReturnType<typeof filesControllerMetadata>>,
  TError = unknown,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filesControllerMetadata>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFilesControllerMetadataQueryKey(token);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof filesControllerMetadata>>
  > = ({ signal }) => filesControllerMetadata(token, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!token,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof filesControllerMetadata>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FilesControllerMetadataQueryResult = NonNullable<
  Awaited<ReturnType<typeof filesControllerMetadata>>
>;
export type FilesControllerMetadataQueryError = unknown;

export function useFilesControllerMetadata<
  TData = Awaited<ReturnType<typeof filesControllerMetadata>>,
  TError = unknown,
>(
  token: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filesControllerMetadata>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerMetadata>>,
          TError,
          Awaited<ReturnType<typeof filesControllerMetadata>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFilesControllerMetadata<
  TData = Awaited<ReturnType<typeof filesControllerMetadata>>,
  TError = unknown,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filesControllerMetadata>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerMetadata>>,
          TError,
          Awaited<ReturnType<typeof filesControllerMetadata>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFilesControllerMetadata<
  TData = Awaited<ReturnType<typeof filesControllerMetadata>>,
  TError = unknown,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filesControllerMetadata>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFilesControllerMetadata<
  TData = Awaited<ReturnType<typeof filesControllerMetadata>>,
  TError = unknown,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filesControllerMetadata>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFilesControllerMetadataQueryOptions(token, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const filesControllerVerify = (
  token: string,
  verifyPasswordDto: VerifyPasswordDto,
  signal?: AbortSignal,
) => {
  return customInstance<VerifyPasswordResultDto>({
    url: `/api/files/${token}/verify`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: verifyPasswordDto,
    signal,
  });
};

export const getFilesControllerVerifyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof filesControllerVerify>>,
    TError,
    { token: string; data: VerifyPasswordDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof filesControllerVerify>>,
  TError,
  { token: string; data: VerifyPasswordDto },
  TContext
> => {
  const mutationKey = ["filesControllerVerify"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof filesControllerVerify>>,
    { token: string; data: VerifyPasswordDto }
  > = (props) => {
    const { token, data } = props ?? {};

    return filesControllerVerify(token, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type FilesControllerVerifyMutationResult = NonNullable<
  Awaited<ReturnType<typeof filesControllerVerify>>
>;
export type FilesControllerVerifyMutationBody = VerifyPasswordDto;
export type FilesControllerVerifyMutationError = unknown;

export const useFilesControllerVerify = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof filesControllerVerify>>,
      TError,
      { token: string; data: VerifyPasswordDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof filesControllerVerify>>,
  TError,
  { token: string; data: VerifyPasswordDto },
  TContext
> => {
  const mutationOptions = getFilesControllerVerifyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const filesControllerDownload = (
  token: string,
  signal?: AbortSignal,
) => {
  return customInstance<Blob>({
    url: `/api/files/${token}/download`,
    method: "GET",
    responseType: "blob",
    signal,
  });
};

export const getFilesControllerDownloadQueryKey = (token?: string) => {
  return [`/api/files/${token}/download`] as const;
};

export const getFilesControllerDownloadQueryOptions = <
  TData = Awaited<ReturnType<typeof filesControllerDownload>>,
  TError = unknown,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filesControllerDownload>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getFilesControllerDownloadQueryKey(token);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof filesControllerDownload>>
  > = ({ signal }) => filesControllerDownload(token, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!token,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof filesControllerDownload>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type FilesControllerDownloadQueryResult = NonNullable<
  Awaited<ReturnType<typeof filesControllerDownload>>
>;
export type FilesControllerDownloadQueryError = unknown;

export function useFilesControllerDownload<
  TData = Awaited<ReturnType<typeof filesControllerDownload>>,
  TError = unknown,
>(
  token: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filesControllerDownload>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerDownload>>,
          TError,
          Awaited<ReturnType<typeof filesControllerDownload>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFilesControllerDownload<
  TData = Awaited<ReturnType<typeof filesControllerDownload>>,
  TError = unknown,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filesControllerDownload>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesControllerDownload>>,
          TError,
          Awaited<ReturnType<typeof filesControllerDownload>>
        >,
        "initialData"
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useFilesControllerDownload<
  TData = Awaited<ReturnType<typeof filesControllerDownload>>,
  TError = unknown,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filesControllerDownload>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useFilesControllerDownload<
  TData = Awaited<ReturnType<typeof filesControllerDownload>>,
  TError = unknown,
>(
  token: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof filesControllerDownload>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getFilesControllerDownloadQueryOptions(token, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const filesControllerRemove = (id: string) => {
  return customInstance<void>({ url: `/api/files/${id}`, method: "DELETE" });
};

export const getFilesControllerRemoveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof filesControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof filesControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["filesControllerRemove"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof filesControllerRemove>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return filesControllerRemove(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type FilesControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof filesControllerRemove>>
>;

export type FilesControllerRemoveMutationError = unknown;

export const useFilesControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof filesControllerRemove>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof filesControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getFilesControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
